site_name: Proyecto de Leonardo Jesús Arévalo Abellán
site_url: https://K6SSL69.github.io/proyecto-mkdocs/
theme:
  name: material

nav:
  - Inicio: index.md
  - Formacion y experiencia: formacion.md
  - Preoyectos: proyectos.md
  - Contacto: contacto.md 

